---
kind: pipeline
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: vbrandl/hits-of-code
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    ref:
      - refs/heads/master
      - refs/tags/v*
---
kind: signature
hmac: 36c14cd35c5abe274025760c9ca34f198d392be0c31435ad58cb9ecaa0abef2a

...
