[package]
name = "hoc"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha.4"
badge = "0.2.0"
bytes = "0.4.12"
futures = "0.1.25"
git2 = "0.8.0"
lazy_static = "1.3.0"
openssl-probe = "0.1.2"
pretty_env_logger = "0.3.0"
reqwest = "0.9.15"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
structopt = "0.2.15"
