[package]
name = "hoc"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha.4"
git2 = "0.8.0"
badge = "0.2.0"
openssl-probe = "0.1.2"
structopt = "0.2.15"
pretty_env_logger = "0.3.0"
